modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
#issueTrackerURL="https://github.com/Spitfox/ChestPresents/issues"
[[mods]]
modId = "chestpresents"
version = "0.1"
displayName = "Present Block"
#updateJSONURL="" auto update checker
displayURL="https://www.curseforge.com/minecraft/mc-mods/present-block"
logoFile="logo.png"
credits="Spitfox"
authors = "JustusWalterHelk, lu3arm"
displayTest="MATCH_VERSION"
description = '''Allows the player to turn a chest into a gift. You will need a wrapping paper.'''
[[dependencies.chestpresents]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.chestpresents]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"