modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
#issueTrackerURL="https://"
[[mods]]
modId = "chestpresents"
version = "${file.jarVersion}"
displayName = "Chestpresents"
#updateJSONURL="https://"
#displayURL="https://"
#logoFile="chestpresents.png"
#credits=""
authors = "JustusWalterHelk"
#displayTest="MATCH_VERSION"
description = '''
Allows the player to turn a chest into a gift
'''
[[dependencies.chestpresents]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.chestpresents]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"